// orangeVarietyTypes.ts
export enum OrangeVarietyEnum {
  Ambiance = "Ambiance",
  BloodOrange = "Blood Orange",
  CaliforniaValencia = "California Valencia",
  CaraCara = "Cara Cara",
  Clementine = "Clementine",
  SeedlessClementine = "Clementine (Seedless)",
  Hamlin = "Hamlin",
  HoneyTangerine = "Honey Tangerine",
  Jaffa = "Jaffa",
  MidsweetHybrid = "Midsweet (Hybrid)",
  MinneolaHybrid = "Minneola (Hybrid)",
  MoroBlood = "Moro (Blood)",
  MurcottHybrid = "Murcott (Hybrid)",
  Navel = "Navel",
  EarlySeasonNavel = "Navel (Early Season)",
  LateSeasonNavel = "Navel (Late Season)",
  OrtaniqueHybrid = "Ortanique (Hybrid)",
  SatsumaMandarin = "Satsuma Mandarin",
  StarRuby = "Star Ruby",
  TangeloHybrid = "Tangelo (Hybrid)",
  Tangerine = "Tangerine",
  Temple = "Temple",
  Valencia = "Valencia",
  WashingtonNavel = "Washington Navel",
}
